//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaKinematics
{
    [Serializable]
    public class AllJointPosMsg : Message
    {
        public const string k_RosMessageName = "panda_kinematics/AllJointPos";
        public override string RosMessageName => k_RosMessageName;

        //  8x3 matrix stored row-major
        public double[] data;

        public AllJointPosMsg()
        {
            this.data = new double[24];
        }

        public AllJointPosMsg(double[] data)
        {
            this.data = data;
        }

        public static AllJointPosMsg Deserialize(MessageDeserializer deserializer) => new AllJointPosMsg(deserializer);

        private AllJointPosMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(double), 24);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "AllJointPosMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
