//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaKinematics
{
    [Serializable]
    public class JointCommandMsg : Message
    {
        public const string k_RosMessageName = "panda_kinematics/JointCommand";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double[] joint_angles;
        public double gripper_pos;
        public string command_type;

        public JointCommandMsg()
        {
            this.header = new Std.HeaderMsg();
            this.joint_angles = new double[7];
            this.gripper_pos = 0.0;
            this.command_type = "";
        }

        public JointCommandMsg(Std.HeaderMsg header, double[] joint_angles, double gripper_pos, string command_type)
        {
            this.header = header;
            this.joint_angles = joint_angles;
            this.gripper_pos = gripper_pos;
            this.command_type = command_type;
        }

        public static JointCommandMsg Deserialize(MessageDeserializer deserializer) => new JointCommandMsg(deserializer);

        private JointCommandMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_angles, sizeof(double), 7);
            deserializer.Read(out this.gripper_pos);
            deserializer.Read(out this.command_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.joint_angles);
            serializer.Write(this.gripper_pos);
            serializer.Write(this.command_type);
        }

        public override string ToString()
        {
            return "JointCommandMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_angles: " + System.String.Join(", ", joint_angles.ToList()) +
            "\ngripper_pos: " + gripper_pos.ToString() +
            "\ncommand_type: " + command_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
